language: node_js

node_js:
  - "5.11.1"

python:
  - "2.7"

cache:
  directories:
    - node_modules

addons:
  firefox: "46.0"

before_install:
  # see https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16 -extension RANDR"
  - export PATH="$PATH:$HOME/.rvm/bin"
  - pip -V
  - sleep 3

install:
  - npm config set spin false
  - npm install
  - sudo pip install -r requirements.txt

before_script:
  - export FIREFOX_BIN=`which firefox`
  - export JPM_FIREFOX_BINARY=`which firefox`
  - firefox -v
  - echo $JPM_FIREFOX_BINARY

script:
  - npm run travis

deploy:
  - provider: script
    skip_cleanup: true
    script: bin/continuous-integration.sh dev
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: bin/continuous-integration.sh prerelease
    on:
      branch: release-1.7.0

notifications:
  email: false
